### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by BangShiuh** [yuezk/GlobalProtect-openconnect#129]
`sudo add-apt-repository ppa:yuezk/globalprotect-openconnect`

A GlobalProtect VPN client (GUI) for Linux based on OpenConnect and built with Qt5, supports SAML auth mode.
 More info: https://launchpad.net/~yuezk/+archive/ubuntu/globalprotect-openconnect
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 191, in <module>
    if not sp.add_source_from_shortcut(shortcut, options.enable_source):
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 773, in add_source_from_shortcut
    self.set_modified_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 498, in set_modified_sourceslist
    self.save_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 664, in save_sourceslist
    self.sourceslist.save()
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 430, in save
    files[source.file] = open(source.file, "w")
FileNotFoundError: [Errno 2] No such file or directory: '/etc/apt/sources.list.d/yuezk-ubuntu-globalprotect-openconnect-focal.list'

**Comment by yuezk** [comment]
I can install it in my VM ubuntu 20.04, please try to remove the https://launchpad.net/~dwmw2/+archive/ubuntu/openconnect repo and retry it.

**Comment by yuezk** [comment]
I can install it in my VM ubuntu 20.04, please try to remove the https://launchpad.net/~dwmw2/+archive/ubuntu/openconnect repo and retry it.

**Comment by yuezk** [comment]
I can install it in my VM ubuntu 20.04 successfully. Please remove the https://launchpad.net/~dwmw2/+archive/ubuntu/openconnect repo and retry it.
