### ISSUE TITLE
with fedora 39 does not work

### ISSUE THREAD

**Issue by mauriziomarini** [yuezk/GlobalProtect-openconnect#269]
with fedora 39 I get this:

Traceback (most recent call last):
  File "/usr/lib64/python3.12/importlib/metadata/__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maurizio/.local/bin/gp-saml-gui", line 33, in <module>
    sys.exit(load_entry_point('gp-saml-gui==0.1', 'console_scripts', 'gp-saml-gui')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maurizio/.local/bin/gp-saml-gui", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/metadata/__init__.py", line 861, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/metadata/__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for gp-saml-gui

**Comment by mauriziomarini** [comment]
[SOLVED]
you have to reinstall again

**Comment by mauriziomarini** [comment]
this issue is not openconnect related, sorry

**Comment by mauriziomarini** [comment]
this issue is not openconnect related, sorry
