### ISSUE TITLE
Segmentation fault during gateway authentication

### ISSUE THREAD

**Issue by southpaw94** [yuezk/GlobalProtect-openconnect#38]
I'm seeing a segmentation fault immediately after pressing "Connect". This didn't start happening until yesterday. I tried uninstalling/reinstalling globalprotect-openconnect from the AUR to no avail. Looks like the server is responding with "Invalid username or password" before I even get to the SAML authentication screen...

>2020-12-01 08:36:44.673 INFO  [3820] [main@22] GlobalProtect started, version: v1.2.5
>2020-12-01 08:36:44.776 INFO  [3820] [GPClient::populateGatewayMenu@100] Populating the Switch Gateway menu...
2020-12-01 08:36:45.957 INFO  [3820] [GPClient::populateGatewayMenu@100] Populating the Switch Gateway menu...
2020-12-01 08:36:46.649 INFO  [3820] [GPClient::doConnect@205] Start connecting...
2020-12-01 08:36:46.649 INFO  [3820] [GPClient::doConnect@221] Start gateway login using the previously saved gateway...
2020-12-01 08:36:46.650 INFO  [3820] [GPClient::gatewayLogin@316] Performing gateway login...
2020-12-01 08:36:46.655 INFO  [3820] [GatewayAuthenticator::authenticate@26] Start gateway authentication...
2020-12-01 08:36:46.655 INFO  [3820] [GatewayAuthenticator::login@38] Trying to login the gateway at https://vpn.stryker.com/ssl-vpn/login.esp with prot=https%3A&server=&inputSrc=&jnlpReady=jnlpReady&computer=arch-precision7520&ok=Login&direct=yes&clientVer=4100&os-version=Arch Linux&clientos=Linux&portal-prelogonuserauthcookie=&prelogin-cookie=&ipv6-support=yes&user=&passwd=&portal-userauthcookie=
2020-12-01 08:36:47.290 INFO  [3820] [gpclient::helper::parseGatewayResponse@50] Start parsing the gateway response...
2020-12-01 08:36:47.290 INFO  [3820] [gpclient::helper::parseGatewayResponse@51] The gateway response is: 
var respStatus = "Error";
var respMsg = "Authentication failure: Invalid username or password";
thisForm.inputStr.value = "";

>Segmentation fault (core dumped)

Update: sorry - adding code does not seem to be working for me so I'm not sure how to get the log formatted nicely.

**Comment by southpaw94** [comment]
I don't know where the settings are stored (I deleted all files in ~/.cache/GlobalProtect-openconnect, ~/.cache/gpclient, and ~/.local/share/gpclient and reinstalled), but resetting via the applet finally did the trick and I'm able to log in again. I didn't know about that option before digging into the code.

**Comment by mikedld** [comment]
There were some changes around this area in #35 which were included in v1.2.6 (your log states you're using v1.2.5). Could you try the latest version and report back?

**Comment by hrk** [comment]
Hello, I have the same issue with 1.2.7 (or, better yet, I'm running from master).
I'm running gpclient directly from the source tree (make but not make install), manually starting gpclient (no gpservice, should I?)
The following log has been recorded after clearing all settings (through the applet) and then restarting the gpclient.
After entering the gateway address (replaced w/ vpn.DOMAIN.com in the log) I was shown a popup to insert my company email and password. From the logs, the email was correctly translated to the corresponing user (replaced w/ <MYDOMAIN>\<MYUSERNAME> in the log) through Microsoft's sts functionality, then there's an empty response and the segmentation fault.
There's MFA set up server side, so I expected a second popup asking me to input a verification code.

```
luca@E0557546 ~/Documents/external/GlobalProtect-openconnect $ GPClient/gpclient 
2021-03-18 09:50:33.285 INFO  [11891] [main@22] GlobalProtect started, version: v1.2.7
2021-03-18 09:50:33.425 INFO  [11891] [GPClient::populateGatewayMenu@100] Populating the Switch Gateway menu...
2021-03-18 09:50:38.881 INFO  [11891] [GPClient::populateGatewayMenu@100] Populating the Switch Gateway menu...
2021-03-18 09:50:38.967 INFO  [11891] [GPClient::doConnect@205] Start connecting...
2021-03-18 09:50:38.967 INFO  [11891] [GPClient::doConnect@226] Start portal login...
2021-03-18 09:50:38.970 INFO  [11891] [PortalAuthenticator::authenticate@29] Preform portal prelogin at https://vpn.DOMAIN.com/global-protect/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux
2021-03-18 09:50:39.399 INFO  [11891] [PortalAuthenticator::onPreloginFinished@46] Portal prelogin succeeded.
2021-03-18 09:50:39.399 INFO  [11891] [PreloginResponse::parse@26] Start parsing the prelogin response...
2021-03-18 09:50:39.399 INFO  [11891] [PortalAuthenticator::onPreloginFinished@50] Finished parsing the prelogin response. The region field is: IT
2021-03-18 09:50:39.399 INFO  [11891] [PortalAuthenticator::samlAuth@117] Trying to perform SAML login with saml-method REDIRECT

DevTools listening on ws://127.0.0.1:12315/devtools/browser/a323d642-fa17-4e17-b56b-19f77d8c66ba
Xlib: sequence lost (0x10339 > 0x33b) in reply type 0x0!
Xlib: sequence lost (0x10356 > 0x358) in reply type 0x0!
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:12315
Xlib: sequence lost (0x10368 > 0x36a) in reply type 0x0!
Xlib: sequence lost (0x1036f > 0x371) in reply type 0x0!
Xlib: sequence lost (0x10379 > 0x37b) in reply type 0x0!
2021-03-18 09:50:39.813 INFO  [11891] [SAMLLoginWindow::onResponseReceived@64] Response received from https://sts.DOMAIN.com/adfs/ls/?SAMLRequest=hVFNb4JAEP0rZO%2B4K6yKEyGheqiJTYnQHnpptrBWEpilO4vpzy9qa%2B3FHifzPua9WZBqmw7S3u1xqz96Tc77bBskOC1i1lsEo6gmQNVqAldCnj5sIBgJ6KxxpjQN81IibV1tcGmQ%2BlbbXNtDXeqn7SZme%2Bc6As4PHY406mZUmhakDPlRKBA8z3i6zJm3GsxrVEeZXxI5upC4qnbEG%2BLMW69i9jqO5KwSO1kJOQuqsJzKiZ7Iai6l1HIayQFG1Os1klPoYhaIYOyL0B9HhYhgIiCcvzAv%2B05xV2NV4%2FvtyG9nEMF9UWR%2B9pgXzHvWlk43DwCWLI7FwcnYXlV5W1b99MeS%2F9ta8CuL5Dz9fWHyBQ%3D%3D&RelayState=R4ogAJuALmA0MTljYjZkZDI4NmUzZTA5YjgxMGYzMmMwNTA5ZGU3OQ%3D%3D&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=WC66NUSivLnDsuw32RdsbdX2zfNkZgk30eCKoY%2FhaLiDCZErE15DIgOywCMAm7DDqZVaPzwVl4n0IdltH3QOWrwb%2BsghNGm38WV5gV8%2FoC21Unbm5DokrR7klCbh%2BzUq2efhjKbVvHRVUzOmFOFyGSk2npJE8H%2BEQyx1c7t4VOwPN76maW0SpQF1ldt%2FIvV7nLHTCWSgcwNTzUZLCSJZbN%2FJP9TRbbNiFCaI2VzONVPSrqMsyspruy%2FDYq6djgmdMKcc%2BxkRZtKw0IRb5voC9jaSi08w9MikX0B53K6kz5nSVabmVMHw%2ByIu60VtIqKgpG9Zo0aONagbAhCzyHFVhQ%3D%3D
Xlib: sequence lost (0x10400 > 0x403) in reply type 0x0!
js: Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.
2021-03-18 09:50:40.085 INFO  [11891] [SAMLLoginWindow::onLoadFinished@98] Load finished https://sts.DOMAIN.com/adfs/ls/?SAMLRequest=hVFNb4JAEP0rZO%2B4K6yKEyGheqiJTYnQHnpptrBWEpilO4vpzy9qa%2B3FHifzPua9WZBqmw7S3u1xqz96Tc77bBskOC1i1lsEo6gmQNVqAldCnj5sIBgJ6KxxpjQN81IibV1tcGmQ%2BlbbXNtDXeqn7SZme%2Bc6As4PHY406mZUmhakDPlRKBA8z3i6zJm3GsxrVEeZXxI5upC4qnbEG%2BLMW69i9jqO5KwSO1kJOQuqsJzKiZ7Iai6l1HIayQFG1Os1klPoYhaIYOyL0B9HhYhgIiCcvzAv%2B05xV2NV4%2FvtyG9nEMF9UWR%2B9pgXzHvWlk43DwCWLI7FwcnYXlV5W1b99MeS%2F9ta8CuL5Dz9fWHyBQ%3D%3D&RelayState=R4ogAJuALmA0MTljYjZkZDI4NmUzZTA5YjgxMGYzMmMwNTA5ZGU3OQ%3D%3D&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=WC66NUSivLnDsuw32RdsbdX2zfNkZgk30eCKoY%2FhaLiDCZErE15DIgOywCMAm7DDqZVaPzwVl4n0IdltH3QOWrwb%2BsghNGm38WV5gV8%2FoC21Unbm5DokrR7klCbh%2BzUq2efhjKbVvHRVUzOmFOFyGSk2npJE8H%2BEQyx1c7t4VOwPN76maW0SpQF1ldt%2FIvV7nLHTCWSgcwNTzUZLCSJZbN%2FJP9TRbbNiFCaI2VzONVPSrqMsyspruy%2FDYq6djgmdMKcc%2BxkRZtKw0IRb5voC9jaSi08w9MikX0B53K6kz5nSVabmVMHw%2ByIu60VtIqKgpG9Zo0aONagbAhCzyHFVhQ%3D%3D
2021-03-18 09:51:00.363 INFO  [11891] [SAMLLoginWindow::onResponseReceived@64] Response received from https://sts.DOMAIN.com/adfs/ls/?SAMLRequest=hVFNb4JAEP0rZO%2B4K6yKEyGheqiJTYnQHnpptrBWEpilO4vpzy9qa%2B3FHifzPua9WZBqmw7S3u1xqz96Tc77bBskOC1i1lsEo6gmQNVqAldCnj5sIBgJ6KxxpjQN81IibV1tcGmQ%2BlbbXNtDXeqn7SZme%2Bc6As4PHY406mZUmhakDPlRKBA8z3i6zJm3GsxrVEeZXxI5upC4qnbEG%2BLMW69i9jqO5KwSO1kJOQuqsJzKiZ7Iai6l1HIayQFG1Os1klPoYhaIYOyL0B9HhYhgIiCcvzAv%2B05xV2NV4%2FvtyG9nEMF9UWR%2B9pgXzHvWlk43DwCWLI7FwcnYXlV5W1b99MeS%2F9ta8CuL5Dz9fWHyBQ%3D%3D&RelayState=R4ogAJuALmA0MTljYjZkZDI4NmUzZTA5YjgxMGYzMmMwNTA5ZGU3OQ%3D%3D&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=WC66NUSivLnDsuw32RdsbdX2zfNkZgk30eCKoY%2FhaLiDCZErE15DIgOywCMAm7DDqZVaPzwVl4n0IdltH3QOWrwb%2BsghNGm38WV5gV8%2FoC21Unbm5DokrR7klCbh%2BzUq2efhjKbVvHRVUzOmFOFyGSk2npJE8H%2BEQyx1c7t4VOwPN76maW0SpQF1ldt%2FIvV7nLHTCWSgcwNTzUZLCSJZbN%2FJP9TRbbNiFCaI2VzONVPSrqMsyspruy%2FDYq6djgmdMKcc%2BxkRZtKw0IRb5voC9jaSi08w9MikX0B53K6kz5nSVabmVMHw%2ByIu60VtIqKgpG9Zo0aONagbAhCzyHFVhQ%3D%3D&client-request-id=9c818ee9-4460-44ca-0c87-0080040000dd
2021-03-18 09:51:00.372 INFO  [11891] [SAMLLoginWindow::onLoadFinished@98] Load finished https://sts.DOMAIN.com/adfs/ls/?SAMLRequest=hVFNb4JAEP0rZO%2B4K6yKEyGheqiJTYnQHnpptrBWEpilO4vpzy9qa%2B3FHifzPua9WZBqmw7S3u1xqz96Tc77bBskOC1i1lsEo6gmQNVqAldCnj5sIBgJ6KxxpjQN81IibV1tcGmQ%2BlbbXNtDXeqn7SZme%2Bc6As4PHY406mZUmhakDPlRKBA8z3i6zJm3GsxrVEeZXxI5upC4qnbEG%2BLMW69i9jqO5KwSO1kJOQuqsJzKiZ7Iai6l1HIayQFG1Os1klPoYhaIYOyL0B9HhYhgIiCcvzAv%2B05xV2NV4%2FvtyG9nEMF9UWR%2B9pgXzHvWlk43DwCWLI7FwcnYXlV5W1b99MeS%2F9ta8CuL5Dz9fWHyBQ%3D%3D&RelayState=R4ogAJuALmA0MTljYjZkZDI4NmUzZTA5YjgxMGYzMmMwNTA5ZGU3OQ%3D%3D&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=WC66NUSivLnDsuw32RdsbdX2zfNkZgk30eCKoY%2FhaLiDCZErE15DIgOywCMAm7DDqZVaPzwVl4n0IdltH3QOWrwb%2BsghNGm38WV5gV8%2FoC21Unbm5DokrR7klCbh%2BzUq2efhjKbVvHRVUzOmFOFyGSk2npJE8H%2BEQyx1c7t4VOwPN76maW0SpQF1ldt%2FIvV7nLHTCWSgcwNTzUZLCSJZbN%2FJP9TRbbNiFCaI2VzONVPSrqMsyspruy%2FDYq6djgmdMKcc%2BxkRZtKw0IRb5voC9jaSi08w9MikX0B53K6kz5nSVabmVMHw%2ByIu60VtIqKgpG9Zo0aONagbAhCzyHFVhQ%3D%3D&client-request-id=9c818ee9-4460-44ca-0c87-0080040000dd
2021-03-18 09:51:00.629 INFO  [11891] [SAMLLoginWindow::onResponseReceived@64] Response received from https://vpn.DOMAIN.com/SAML20/SP/ACS
2021-03-18 09:51:00.630 INFO  [11891] [SAMLLoginWindow::onResponseReceived@67] Got username from SAML response headers <MYDOMAIN>\<MYUSERNAME>
2021-03-18 09:51:00.630 INFO  [11891] [SAMLLoginWindow::onResponseReceived@72] Got prelogin-cookie from SAML response headers hE+oBJlbsGgPOKr+6ZjHcKLD9vXFegMVfnSqCS31C/b7iDirx5NTFR5CQaQXC+xS
2021-03-18 09:51:00.630 INFO  [11891] [SAMLLoginWindow::onResponseReceived@84] Got the SAML authentication information successfully. username: <MYDOMAIN>\<MYUSERNAME>, preloginCookie: hE+oBJlbsGgPOKr+6ZjHcKLD9vXFegMVfnSqCS31C/b7iDirx5NTFR5CQaQXC+xS, userAuthCookie: 
2021-03-18 09:51:00.630 INFO  [11891] [PortalAuthenticator::onSAMLLoginSuccess@131] SAML login succeeded, got the prelogin-cookie hE+oBJlbsGgPOKr+6ZjHcKLD9vXFegMVfnSqCS31C/b7iDirx5NTFR5CQaQXC+xS
2021-03-18 09:51:00.630 INFO  [11891] [PortalAuthenticator::fetchConfig@157] Fetching the portal config from https://vpn.DOMAIN.com/global-protect/getconfig.esp for user: <MYDOMAIN>\<MYUSERNAME>
2021-03-18 09:51:00.724 INFO  [11891] [SAMLLoginWindow::onLoadFinished@98] Load finished https://vpn.DOMAIN.com/SAML20/SP/ACS
2021-03-18 09:51:00.819 INFO  [11891] [PortalAuthenticator::onFetchConfigFinished@183] Fetch the portal config succeeded.
2021-03-18 09:51:00.819 INFO  [11891] [PortalConfigResponse::parse@20] Start parsing the portal configuration...
2021-03-18 09:51:00.820 INFO  [11891] [PortalConfigResponse::parse@32] Start reading portal-userauthcookie
2021-03-18 09:51:00.820 INFO  [11891] [PortalConfigResponse::parse@35] Start reading portal-prelogonuserauthcookie
2021-03-18 09:51:00.820 INFO  [11891] [PortalConfigResponse::parse@42] Finished parsing portal configuration.
2021-03-18 09:51:00.820 INFO  [11891] [GPClient::onPortalSuccess@257] Portal authentication succeeded.
2021-03-18 09:51:00.820 INFO  [11891] [GPClient::onPortalSuccess@261] No gateway found in portal configuration, treat the portal address as a gateway.
2021-03-18 09:51:00.820 INFO  [11891] [GPClient::tryGatewayLogin@297] Try to preform login on the the gateway interface...
2021-03-18 09:51:00.820 INFO  [11891] [GPClient::setAllGateways@384] Updating all the gateways...
2021-03-18 09:51:00.820 INFO  [11891] [GPClient::populateGatewayMenu@100] Populating the Switch Gateway menu...
2021-03-18 09:51:00.820 INFO  [11891] [GPClient::setCurrentGateway@404] Updating the current gateway to vpn.DOMAIN.com
2021-03-18 09:51:00.820 INFO  [11891] [GPClient::populateGatewayMenu@100] Populating the Switch Gateway menu...
2021-03-18 09:51:00.821 INFO  [11891] [GPClient::gatewayLogin@316] Performing gateway login...
2021-03-18 09:51:00.825 INFO  [11891] [GatewayAuthenticator::authenticate@26] Start gateway authentication...
2021-03-18 09:51:00.825 INFO  [11891] [GatewayAuthenticator::login@38] Trying to login the gateway at https://vpn.DOMAIN.com/ssl-vpn/login.esp with prot=https%3A&server=&inputSrc=&jnlpReady=jnlpReady&computer=E0557546&ok=Login&direct=yes&clientVer=4100&os-version=Gentoo%2FLinux&clientos=Linux&portal-prelogonuserauthcookie=&prelogin-cookie=&ipv6-support=yes&user=&passwd=&portal-userauthcookie=
2021-03-18 09:51:01.138 INFO  [11891] [gpclient::helper::parseGatewayResponse@50] Start parsing the gateway response...
2021-03-18 09:51:01.138 INFO  [11891] [gpclient::helper::parseGatewayResponse@51] The gateway response is: 
var respStatus = "Error";
var respMsg = "Authentication failure: Invalid username or password";
thisForm.inputStr.value = "";


Errore di segmentazione
```

**Comment by elifarley** [comment]
I've been using version **1.2.7** for some time without any problems, but yesterday I got the same error:

```
gpclient 
2021-04-16 11:48:34.187 INFO  [3749] [main@22] GlobalProtect started, version: v1.2.7
2021-04-16 11:48:34.275 INFO  [3749] [GPClient::populateGatewayMenu@100] Populating the Switch Gateway menu...
2021-04-16 11:48:37.131 INFO  [3749] [GPClient::populateGatewayMenu@100] Populating the Switch Gateway menu...
2021-04-16 11:48:38.607 INFO  [3749] [GPClient::doConnect@205] Start connecting...
2021-04-16 11:48:38.607 INFO  [3749] [GPClient::doConnect@221] Start gateway login using the previously saved gateway...
2021-04-16 11:48:38.607 INFO  [3749] [GPClient::gatewayLogin@316] Performing gateway login...
2021-04-16 11:48:38.616 INFO  [3749] [GatewayAuthenticator::authenticate@26] Start gateway authentication...
2021-04-16 11:48:38.616 INFO  [3749] [GatewayAuthenticator::login@38] Trying to login the gateway at https://my.domain.com/ssl-vpn/login.esp with prot=https%3A&server=&inputSrc=&jnlpReady=jnlpReady&computer=xxLQ4Y2&ok=Login&direct=yes&clientVer=4100&os-version=Ubuntu 18.04.4 LTS&clientos=Linux&portal-prelogonuserauthcookie=&prelogin-cookie=&ipv6-support=yes&user=&passwd=&portal-userauthcookie=
2021-04-16 11:48:38.634 INFO  [3749] [GPClient::populateGatewayMenu@100] Populating the Switch Gateway menu...
2021-04-16 11:48:38.977 INFO  [3749] [gpclient::helper::parseGatewayResponse@50] Start parsing the gateway response...
2021-04-16 11:48:38.977 INFO  [3749] [gpclient::helper::parseGatewayResponse@51] The gateway response is: 
var respStatus = "Error";
var respMsg = "Authentication failure: Invalid username or password";
thisForm.inputStr.value = "";

Segmentation fault (core dumped)
```

**Comment by connor-craig** [comment]
I'm having the same issue as above, its was working perfectly on **1.2.8** (running from master). Any idea how to fix it? I also cant find any way to delete the settings in the applet as described above, and deleting those folders didnt do the trick either.

`gpclient
2021-05-03 10:22:17.440 INFO  [7498] [main@22] GlobalProtect started, version: v1.2.8
QSocketNotifier: Can only be used with threads started with QThread
2021-05-03 10:22:17.579 INFO  [7498] [GPClient::populateGatewayMenu@100] Populating the Switch Gateway menu...
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
2021-05-03 10:22:28.906 INFO  [7498] [GPClient::populateGatewayMenu@100] Populating the Switch Gateway menu...
2021-05-03 10:25:58.267 INFO  [7498] [GPClient::doConnect@205] Start connecting...
2021-05-03 10:25:58.267 INFO  [7498] [GPClient::doConnect@221] Start gateway login using the previously saved gateway...
2021-05-03 10:25:58.267 INFO  [7498] [GPClient::gatewayLogin@316] Performing gateway login...
2021-05-03 10:25:58.276 INFO  [7498] [GatewayAuthenticator::authenticate@26] Start gateway authentication...
2021-05-03 10:25:58.276 INFO  [7498] [GatewayAuthenticator::login@38] Trying to login the gateway at https://DOMAIN/ssl-vpn/login.esp with prot=https%3A&server=&inputSrc=&jnlpReady=jnlpReady&computer=fedora&ok=Login&direct=yes&clientVer=4100&os-version=Fedora 34 %28Workstation Edition%29&clientos=Linux&portal-prelogonuserauthcookie=&prelogin-cookie=&ipv6-support=yes&user=&passwd=&portal-userauthcookie=
2021-05-03 10:25:58.653 INFO  [7498] [gpclient::helper::parseGatewayResponse@50] Start parsing the gateway response...
2021-05-03 10:25:58.653 INFO  [7498] [gpclient::helper::parseGatewayResponse@51] The gateway response is: 
var respStatus = "Error";
var respMsg = "Authentication failure: Invalid username or password";
thisForm.inputStr.value = "";


Segmentation fault (core dumped)`

**Comment by gvacaliuc** [comment]
I was able to resolve this by running `gpclient`, right clicking the applet and then clicking "Reset Settings".

**Comment by pensnarik** [comment]
I can confirm that I have this issue in version 1.2.8 (Arch Linux):

```
2021-07-14 09:38:14.358 INFO  [131024] [gpclient::helper::parseGatewayResponse@50] Start parsing the gateway response...
2021-07-14 09:38:14.359 INFO  [131024] [gpclient::helper::parseGatewayResponse@51] The gateway response is: 
var respStatus = "Error";
var respMsg = "Authentication failure: Invalid username or password";
thisForm.inputStr.value = "";


--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "gpclient" received signal SIGSEGV, Segmentation fault.
0x00007fffee48c922 in QUrlQuery::addQueryItem(QString const&, QString const&) () from /usr/lib/libQt5Core.so.5
```

Stack trace:
```
(gdb) bt
#0  0x00007fffee48c922 in QUrlQuery::addQueryItem(QString const&, QString const&) () at /usr/lib/libQt5Core.so.5
#1  0x00005555555791c5 in gpclient::helper::parseGatewayResponse(QByteArray const&) (xml=...) at gphelper.cpp:64
#2  0x0000555555572a16 in GatewayAuthenticator::onLoginFinished() (this=0x555555de4190) at gatewayauthenticator.cpp:64
#3  0x00007fffee5703bb in  () at /usr/lib/libQt5Core.so.5
#4  0x00007fffee9ae4c5 in  () at /usr/lib/libQt5Network.so.5
#5  0x00007fffee56615f in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#6  0x00007fffef833d62 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#7  0x00007fffee53900a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#8  0x00007fffee53c109 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#9  0x00007fffee592604 in  () at /usr/lib/libQt5Core.so.5
#10 0x00007fffeb36202c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#11 0x00007fffeb3b5b59 in  () at /usr/lib/libglib-2.0.so.0
#12 0x00007fffeb35f781 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#13 0x00007fffee591c36 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#14 0x00007fffee53797c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#15 0x00007fffee53fee4 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#16 0x0000555555568961 in main(int, char**) (argc=<optimized out>, argv=0x7fffffffe4d8) at main.cpp:38
```
