### ISSUE TITLE
add apt repo failed

### ISSUE THREAD

**Issue by Jeane212** [yuezk/GlobalProtect-openconnect#452]
**Describe the bug**
Failed when execute this command`sudo add-apt-repository ppa:yuezk/globalprotect-openconnect`

**Logs**
```
sudo add-apt-repository ppa:yuezk/globalprotect-openconnect
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/add-apt-repository", line 347, in main
    shortcut = handler(source, **shortcut_params)
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 82, in __init__
    if self.lpppa.publish_debug_symbols:
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 107, in lpteam
    self._lpteam = self.lp.people(self.teamname)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 98, in lp
    self._lp = login_func("%s.%s" % (self.__module__, self.__class__.__name__),
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 494, in login_anonymously
    return cls(
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 230, in __init__
    super(Launchpad, self).__init__(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 472, in __init__
    self._wadl = self._browser.get_wadl_application(self._root_uri)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 447, in get_wadl_application
    response, content = self._request(url, media_type=wadl_type)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 389, in _request
    response, content = self._request_and_retry(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 359, in _request_and_retry
    response, content = self._connection.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1693, in request
    (response, new_content) = self._request(
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 144, in _request
    response, content = super(LaunchpadOAuthAwareHttp, self)._request(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 184, in _request
    return super(RestfulHttp, self)._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1363, in _conn_request
    conn.connect()
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1155, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
```

**Environment:**
 - OS: [Ubuntu 22.04]
 - Desktop Environment: [GNOME Shell 42.9]
 - Output of `ps aux | grep 'gnome-keyring\|kwalletd5' | grep -v grep`: [Nothing]
<img width="441" alt="Screenshot 2024-12-10 at 2 28 38 PM" src="https://github.com/user-attachments/assets/387f9f40-c9ab-4985-9432-8012c2d67e02">

 - Is remote SSH? [Yes]

**Comment by blalande** [comment]
I have the same issue on a fresh install of Pikalinux (debian based), use hyprland

**Comment by yuezk** [comment]
You can install it with this command and see what happens.
```bash
curl -o- https://raw.githubusercontent.com/yuezk/GlobalProtect-openconnect/main/scripts/deb-install.sh \
  | bash -s -- 2.3.9
```

**Comment by blalande** [comment]
When using this command I have a dependancy error with libicu74 and libjpeg8 that dont seem to be available

**Comment by yuezk** [comment]
@Jeane212 can you update the `ca-certificates` and try it again?

```
sudo apt install ca-certificates
```

**Comment by Jeane212** [comment]
> @Jeane212 can you update the `ca-certificates` and try it again?
> 
> ```
> sudo apt install ca-certificates
> ```

Here is the result

`sudo apt install ca-certificates
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 gir1.2-javascriptcoregtk-4.0 : Depends: libjavascriptcoregtk-4.0-18 (= 2.46.3-0ubuntu0.22.04.1) but 2.43.3-1 is to be installed
 gir1.2-webkit2-4.0 : Depends: libwebkit2gtk-4.0-37 (= 2.46.3-0ubuntu0.22.04.1) but 2.43.3-1 is to be installed
 libjavascriptcoregtk-4.0-18 : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.8 is to be installed
                               Depends: libicu74 (>= 74.1-1~) but it is not installable
                               Depends: libstdc++6 (>= 13) but 12.3.0-1ubuntu1~22.04 is to be installed
 libwebkit2gtk-4.0-37 : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.8 is to be installed
                        Depends: libgcrypt20 (>= 1.10.0) but 1.9.4-3ubuntu3 is to be installed
                        Depends: libglib2.0-0 (>= 2.75.3) but 2.72.4-0ubuntu2.4 is to be installed
                        Depends: libgstreamer1.0-0 (>= 1.22.0) but 1.20.3-0ubuntu1 is to be installed
                        Depends: libicu74 (>= 74.1-1~) but it is not installable
                        Depends: libstdc++6 (>= 13.1) but 12.3.0-1ubuntu1~22.04 is to be installed
                        Depends: libwebp7 (>= 1.3.2) but 1.2.2-2ubuntu0.22.04.2 is to be installed
                        Depends: libwebpdemux2 (>= 1.3.2) but 1.2.2-2ubuntu0.22.04.2 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).`

After that i execute
`sudo apt --fix-broken install`

And here's the result

`sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libjavascriptcoregtk-4.0-18 libwebkit2gtk-4.0-37
Suggested packages:
  gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-alsa
The following packages will be upgraded:
  libjavascriptcoregtk-4.0-18 libwebkit2gtk-4.0-37
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
Need to get 33.3 MB of archives.
After this operation, 10.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Ign:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libwebkit2gtk-4.0-37 amd64 2.46.3-0ubuntu0.22.04.1
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libjavascriptcoregtk-4.0-18 amd64 2.46.3-0ubuntu0.22.04.1
Err:1 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libwebkit2gtk-4.0-37 amd64 2.46.3-0ubuntu0.22.04.1
  404  Not Found [IP: 185.125.190.81 80]
Err:2 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libjavascriptcoregtk-4.0-18 amd64 2.46.3-0ubuntu0.22.04.1
  404  Not Found [IP: 185.125.190.81 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libwebkit2gtk-4.0-37_2.46.3-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 185.125.190.81 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libjavascriptcoregtk-4.0-18_2.46.3-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 185.125.190.81 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

And user `--fix-missing` is comeback again to `--fix-broken install`

What should i do?

**Comment by yuezk** [comment]
@Jeane212 Ubuntu 22.04 should not use the manual install script. Adding the PPA is the right way to install it.

**Comment by yuezk** [comment]
```
Do you want to continue? [Y/n] Y
Ign:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libwebkit2gtk-4.0-37 amd64 2.46.3-0ubuntu0.22.04.1
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libjavascriptcoregtk-4.0-18 amd64 2.46.3-0ubuntu0.22.04.1
Err:1 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libwebkit2gtk-4.0-37 amd64 2.46.3-0ubuntu0.22.04.1
  404  Not Found [IP: 185.125.190.81 80]
Err:2 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libjavascriptcoregtk-4.0-18 amd64 2.46.3-0ubuntu0.22.04.1
  404  Not Found [IP: 185.125.190.81 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libwebkit2gtk-4.0-37_2.46.3-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 185.125.190.81 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libjavascriptcoregtk-4.0-18_2.46.3-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 185.125.190.81 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

@Jeane212, the log shows that the jammy-updates couldn't find the package. But the package does exist on the jammy repos.

https://launchpad.net/ubuntu/jammy/+package/libjavascriptcoregtk-4.0-18

Can you check your software repository configurations?

**Comment by Jeane212** [comment]
Here's my software configuration

```1 /etc/apt/apt.conf.d/01-vendor-ubuntu     2 /etc/apt/apt.conf.d/01autoremove         3 /etc/cron.daily/apt-compat               4 /etc/logrotate.d/apt```

**Comment by Jeane212** [comment]
> ```
> Do you want to continue? [Y/n] Y
> Ign:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libwebkit2gtk-4.0-37 amd64 2.46.3-0ubuntu0.22.04.1
> Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libjavascriptcoregtk-4.0-18 amd64 2.46.3-0ubuntu0.22.04.1
> Err:1 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libwebkit2gtk-4.0-37 amd64 2.46.3-0ubuntu0.22.04.1
>   404  Not Found [IP: 185.125.190.81 80]
> Err:2 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libjavascriptcoregtk-4.0-18 amd64 2.46.3-0ubuntu0.22.04.1
>   404  Not Found [IP: 185.125.190.81 80]
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libwebkit2gtk-4.0-37_2.46.3-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 185.125.190.81 80]
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libjavascriptcoregtk-4.0-18_2.46.3-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 185.125.190.81 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```
> 
> @Jeane212, the log shows that the jammy-updates couldn't find the package. But the package does exist on the jammy repos.
> 
> https://launchpad.net/ubuntu/jammy/+package/libjavascriptcoregtk-4.0-18
> 
> Can you check your software repository configurations?

I've tried the fetch URL on web browser its return 404

![SmartSelect_20241212_012402_Chrome](https://github.com/user-attachments/assets/27cf53bd-ddc4-48c6-9c20-6ec13496e16e)

**Comment by Jeane212** [comment]
> > @Jeane212 can you update the `ca-certificates` and try it again?
> > ```
> > sudo apt install ca-certificates
> > ```
> 
> Here is the result
> 
> ```
> sudo apt install ca-certificates
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> ca-certificates is already the newest version (20240203~22.04.1).
> You might want to run 'apt --fix-broken install' to correct these.
> The following packages have unmet dependencies:
>  gir1.2-javascriptcoregtk-4.0 : Depends: libjavascriptcoregtk-4.0-18 (= 2.46.3-0ubuntu0.22.04.1) but 2.43.3-1 is to be installed
>  gir1.2-webkit2-4.0 : Depends: libwebkit2gtk-4.0-37 (= 2.46.3-0ubuntu0.22.04.1) but 2.43.3-1 is to be installed
>  libjavascriptcoregtk-4.0-18 : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.8 is to be installed
>                                Depends: libicu74 (>= 74.1-1~) but it is not installable
>                                Depends: libstdc++6 (>= 13) but 12.3.0-1ubuntu1~22.04 is to be installed
>  libwebkit2gtk-4.0-37 : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.8 is to be installed
>                         Depends: libgcrypt20 (>= 1.10.0) but 1.9.4-3ubuntu3 is to be installed
>                         Depends: libglib2.0-0 (>= 2.75.3) but 2.72.4-0ubuntu2.4 is to be installed
>                         Depends: libgstreamer1.0-0 (>= 1.22.0) but 1.20.3-0ubuntu1 is to be installed
>                         Depends: libicu74 (>= 74.1-1~) but it is not installable
>                         Depends: libstdc++6 (>= 13.1) but 12.3.0-1ubuntu1~22.04 is to be installed
>                         Depends: libwebp7 (>= 1.3.2) but 1.2.2-2ubuntu0.22.04.2 is to be installed
>                         Depends: libwebpdemux2 (>= 1.3.2) but 1.2.2-2ubuntu0.22.04.2 is to be installed
> E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
> ```
> 
> After that i execute `sudo apt --fix-broken install`
> 
> And here's the result
> 
> ```
> sudo apt --fix-broken install
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Correcting dependencies... Done
> The following additional packages will be installed:
>   libjavascriptcoregtk-4.0-18 libwebkit2gtk-4.0-37
> Suggested packages:
>   gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-alsa
> The following packages will be upgraded:
>   libjavascriptcoregtk-4.0-18 libwebkit2gtk-4.0-37
> 2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> 2 not fully installed or removed.
> Need to get 33.3 MB of archives.
> After this operation, 10.8 MB of additional disk space will be used.
> Do you want to continue? [Y/n] Y
> Ign:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libwebkit2gtk-4.0-37 amd64 2.46.3-0ubuntu0.22.04.1
> Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libjavascriptcoregtk-4.0-18 amd64 2.46.3-0ubuntu0.22.04.1
> Err:1 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libwebkit2gtk-4.0-37 amd64 2.46.3-0ubuntu0.22.04.1
>   404  Not Found [IP: 185.125.190.81 80]
> Err:2 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libjavascriptcoregtk-4.0-18 amd64 2.46.3-0ubuntu0.22.04.1
>   404  Not Found [IP: 185.125.190.81 80]
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libwebkit2gtk-4.0-37_2.46.3-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 185.125.190.81 80]
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libjavascriptcoregtk-4.0-18_2.46.3-0ubuntu0.22.04.1_amd64.deb  404  Not Found [IP: 185.125.190.81 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```
> 
> And execute `--fix-missing` is comeback again to `--fix-broken install`
> 
> What should i do?

I think the certificate is newest one based on this message

`ca-certificates is already the newest version (20240203~22.04.1).`

**Comment by Jeane212** [comment]
> @Jeane212 can you update the `ca-certificates` and try it again?
> 
> ```
> sudo apt install ca-certificates
> ```


Updated the latest command

```
sudo apt install ca-certificates
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
```

After that i executed `sudo add-apt-repository ppa:yuezk/globalprotect-openconnect` again

The error still same

**Comment by ndisalvio3** [comment]
A gift: https://github.com/ndisalvio3/apt

**Comment by ChristianF88** [comment]
Hi @yuezk, would you happen to have any updates on this? I'm struggeling with the same thing...

```bash
sudo add-apt-repository ppa:yuezk/globalprotect-openconnect
Repository: 'deb https://ppa.launchpadcontent.net/yuezk/globalprotect-openconnect/ubuntu/ bookworm main'
Description:
A GlobalProtect VPN client (GUI) for Linux, based on OpenConnect and Tauri, supports SSO authentication mode.
More info: https://launchpad.net/~yuezk/+archive/ubuntu/globalprotect-openconnect
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Found existing deb entry in /etc/apt/sources.list.d/yuezk-ubuntu-globalprotect-openconnect-bookworm.list
Adding deb entry to /etc/apt/sources.list.d/yuezk-ubuntu-globalprotect-openconnect-bookworm.list
Found existing deb-src entry in /etc/apt/sources.list.d/yuezk-ubuntu-globalprotect-openconnect-bookworm.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/yuezk-ubuntu-globalprotect-openconnect-bookworm.list
Adding key to /etc/apt/trusted.gpg.d/yuezk-ubuntu-globalprotect-openconnect.gpg with fingerprint 7937C393082992E5D6E4A60453FC26B43838D761

...
                                      
Hit:18 https://dl.google.com/linux/chrome/deb stable InRelease                                
Get:20 https://repo.charm.sh/apt * InRelease                                                  
Hit:16 https://deb.goaccess.io bookworm InRelease                       
Err:21 https://ppa.launchpadcontent.net/yuezk/globalprotect-openconnect/ubuntu bookworm Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/yuezk/globalprotect-openconnect/ubuntu bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by yuezk** [comment]
If the PPA is not working, please try to install the `.deb` package from the release page. https://github.com/yuezk/GlobalProtect-openconnect/releases.
